image: $GLOBAL_CI_DOCKER_IMAGE
stages:
  - build
  - test
  - deploy

dev-deploy:
  stage: deploy
  environment: development
  variables:
    APP_DOMAIN_NAME: registry.grechka.digital
    APP_ROOT: ${GRCH_SITES_ROOT}/${APP_DOMAIN_NAME}
  script:
    - cd ${APP_ROOT}/project
    - git pull --ff-only origin master
    - docker exec registry-phpfpm sh -c "make deploy && make clear"
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  tags:
    - ${GRCH_CI_TAG}


